In [5]:
# 필요 모듈 import
import numpy as np

In [6]:
a = np.linspace(1,10,10)
a = a.reshape(2,-1)
a = a.astype("int")
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
b = np.linspace(11,20,10).astype('int')
# b = np.expand_dims(b,axis=-1)
b = b.reshape(2,-1)
b

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
# horizontal stack
np.hstack((a,b))

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [9]:
# vertical stack
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [10]:
# 단순 1개 차원 증가
a[:,np.newaxis]

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]]])

In [11]:
a.sum(), a.var(), a.max(), a.min()

(np.int64(55), np.float64(8.25), np.int64(10), np.int64(1))

In [12]:
a.sum(axis=1), a.sum(axis=0)

(array([15, 40]), array([ 7,  9, 11, 13, 15]))

In [14]:
# %pip install pandas

In [15]:
import pandas as pd

df = pd.DataFrame(a)
df

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [16]:
df.corr()

0    1    2    3    4
0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0  1.0

In [17]:
df = pd.DataFrame(np.vstack((a,b)))
df

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20

In [18]:
df.corr()

0    1    2    3    4
0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0  1.0

In [3]:
import numpy as np

a = np.linspace(0,9,10)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])