# 행렬곱
- i x j @ j x k = i x k

In [3]:
import numpy as np
A = np.array([[3,4,1],[0,5,2]])
B = np.array([[2,0,0],[1,0,5],[4,5,0]])
A@B, np.dot(A,B), np.matmul(A,B)

(array([[14,  5, 20],
        [13, 10, 25]]),
 array([[14,  5, 20],
        [13, 10, 25]]),
 array([[14,  5, 20],
        [13, 10, 25]]))

# 역행렬
- 행렬곱을 통해 단위행렬을 만드는 행렬을 의미
- 행렬식 ad-bc의 결과에 따라 여부 결정
```
([a b],
[c, d])
=> 역행렬
1/(ad-bc) * ([d -b],
              [-c a])
```

In [7]:
np.linalg.inv(B)

array([[ 5.00000000e-01,  0.00000000e+00, -1.38777878e-17],
       [-4.00000000e-01, -0.00000000e+00,  2.00000000e-01],
       [-1.00000000e-01,  2.00000000e-01,  0.00000000e+00]])

In [16]:
C = np.array([[1,2],[3,4]])
C_inverse = np.linalg.inv(C)
C_inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [17]:
# 행렬곱에 따른 결과 점검
C@C_inverse

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [20]:
# 행렬식 or determinate / 결정식
# 해당 값이 0이라면 역행렬을 구성할 수 없음
np.linalg.det(C)

np.float64(-2.0000000000000004)

In [ ]:
D = np.array([[2,3],[4,6]])
# np.linalg.det(D) # 0
# np.linalg.inv(D) # Singular matrix Error => 납작하게 눌린 행렬은 역행렬이 존재하지 않는다

In [24]:
A

array([[3, 4, 1],
       [0, 5, 2]])

In [25]:
B

array([[2, 0, 0],
       [1, 0, 5],
       [4, 5, 0]])