In [53]:
import numpy as np
x = [2,4,6,8]
y = [81,93,91,97]
x = np.array(x)
y = np.array(y)
Y = y.reshape(-1,1).astype(np.uint8)
X = np.stack((x,np.ones(len(x))),axis = 1) # 8행 2열 
X = np.c_[x,np.ones(len(x))].astype(np.uint8) # 8행 2열 => 정방행렬 X
X, Y

(array([[2, 1],
        [4, 1],
        [6, 1],
        [8, 1]], dtype=uint8),
 array([[81],
        [93],
        [91],
        [97]], dtype=uint8))

In [15]:
# (X의 역행렬 @ (X.T @ X)) @ wb = X의 역행렬 @ (X.T @ Y)

In [54]:
X.T, X.transpose()

(array([[2, 4, 6, 8],
        [1, 1, 1, 1]], dtype=uint8),
 array([[2, 4, 6, 8],
        [1, 1, 1, 1]], dtype=uint8))

In [55]:
# X가 정방행렬이 아닐 경우 역행렬을 구할 수 없어 전치행렬(X.T)을 내적시켜서 정방행렬로 만들어준다.
X_ = X.T@X
X_
# np.linalg.inv(X_)@X_ = np.eye(n)형태

array([[120,  20],
       [ 20,   4]], dtype=uint8)

In [58]:
wb = np.linalg.inv(X_) @ X.T @ Y
wb
w,b = wb
w,b # 기울기와 y절편

(array([2.3]), array([79.]))

In [59]:
# 예측값을 구하려면 공식을 구성한다
y_ = x*w + b
y_

array([83.6, 88.2, 92.8, 97.4])

In [41]:
# 에러(잔차)
error = y - y_
error

array([-2.6,  4.8, -1.8, -0.4])

In [63]:
# rmse
error_square = error*error
rmse = ((error_square.sum())/error.size)**0.5
rmse

np.float64(2.8809720581775866)

In [26]:
import numpy as np
X = np.array([2,4,6,8])
Y = np.array([81,93,91,97])
X.reshape(-1,1), Y.reshape(-1,1)

(array([[2],
        [4],
        [6],
        [8]]),
 array([[81],
        [93],
        [91],
        [97]]))

In [18]:
from sklearn.linear_model import LinearRegression
import numpy as np

lr = LinearRegression()
x = [[2],[4],[6],[8]]
y = [[81],[93],[91],[97]]

lr.fit(x,y)

LinearRegression()

In [29]:
lr.coef_, lr.intercept_

(array([[2.3]]), array([79.]))

In [19]:
y_ = lr.predict(x)

In [21]:
error = np.array(y) - y_
error

array([[-2.6],
       [ 4.8],
       [-1.8],
       [-0.4]])

In [23]:
rmse = np.sqrt(((error*error).sum()/len(error)))
rmse

np.float64(2.880972058177584)