In [1]:
import sys
import numpy as np
import cv2

In [2]:
img_path = 'img/neutrophils.png'

In [3]:
src = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

In [4]:
src.shape

(480, 640)

In [5]:
def on_threshold(pos):
    _, dst = cv2.threshold(src, pos, 255, cv2.THRESH_BINARY)
    cv2.imshow('dst', dst)

In [6]:
cv2.imshow('src', src)

cv2.namedWindow('dst')
cv2.createTrackbar('Threshold', 'dst', 0, 255, on_threshold)
cv2.setTrackbarPos('Threshold', 'dst', 128)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
# 적응형이진화
import sys
import numpy as np
import cv2

src = cv2.imread('img/sudoku.jpg', cv2.IMREAD_GRAYSCALE)
src.shape

(563, 558)

In [15]:
def on_trackbar(pos):
    bsize = pos
    if bsize % 2 == 0: bsize = bsize - 1
    if bsize < 3: bsize = 3

    dst = cv2.adaptiveThreshold(src, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                               cv2.THRESH_BINARY, bsize, 5)

    cv2.imshow('dst', dst)

In [16]:
cv2.imshow('src', src)

cv2.namedWindow('dst')
cv2.createTrackbar('Block Size', 'dst', 0, 200, on_trackbar)
cv2.setTrackbarPos('Block Size', 'dst', 11)

cv2.waitKey()
cv2.destroyAllWindows()

In [2]:
src.shape

(4032, 3024)

In [ ]:
import numpy as np
import cv2
src = cv2.imread('img/JS.jpg', cv2.IMREAD_GRAYSCALE)

def on_trackbar(pos):
    bsize = pos
    if bsize % 2 == 0: bsize = bsize - 1
    if bsize < 3: bsize = 3

    dst = cv2.adaptiveThreshold(src, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                               cv2.THRESH_BINARY, bsize, 5)

    cv2.imshow('dst', dst)
    
cv2.namedWindow('dst',cv2.WINDOW_NORMAL)

cv2.imshow('src', src)

cv2.createTrackbar('Block Size', 'dst', 0, 200, on_trackbar)
cv2.setTrackbarPos('Block Size', 'dst', 11)

cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
import numpy as np
import cv2
src = cv2.imread('img/pcb.png', cv2.IMREAD_GRAYSCALE)

def on_trackbar(pos):
    bsize = pos
    if bsize % 2 == 0: bsize = bsize - 1
    if bsize < 3: bsize = 3

    dst = cv2.adaptiveThreshold(src, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                               cv2.THRESH_BINARY_INV, bsize, 5)

    cv2.imshow('dst', dst)
    
cv2.namedWindow('dst',cv2.WINDOW_NORMAL)

cv2.imshow('src', src)

cv2.createTrackbar('Block Size', 'dst', 0, 200, on_trackbar)
cv2.setTrackbarPos('Block Size', 'dst', 11)

cv2.waitKey()
cv2.destroyAllWindows()

In [41]:
# img/scaned_paper.jpg 속 글씨를 선명하게 하기
# 이미지 체크
import numpy as np
import cv2

img_path = 'img/scaned_paper.jpg'
src = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
cv2.imshow('origin',src)

dst_128 = cv2.add(src,150)
dst_128 = np.where(dst>128,255,0).astype(np.uint8)
cv2.imshow('dst_128',dst_128)

dst = cv2.add(src,110)
dst = np.where(dst>dst.mean(),255,0).astype(np.uint8)
cv2.imshow('brighter',dst)

# 1. 평균치를 기준으로 단순하게 작업해보기
dst1 = np.where(src<src.mean(),0,255).astype(np.uint8)
cv2.imshow('npwhere',dst1) # 선명하지 않음

# 2. threshhold 활용
_, dst2 = cv2.threshold(src, -1, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
cv2.imshow('threshhold', dst2)

# 3. Adaptivethreshhold 활용
dst_adap = cv2.adaptiveThreshold(src, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 7, 10)
cv2.imshow('adaptive', dst_adap)

cv2.waitKey()
cv2.destroyAllWindows()

# 선생님 풀이

In [ ]:
img = cv2.imread('img/scaned_paper.jpg', cv2.IMREAD_GRAYSCALE)
img.shape

(450, 400)

In [40]:
cv2.threshold(img, 130, 255, cv2.THRESH_BINARY)

(130.0,
 array([[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [  0,   0,   0, ..., 255, 255, 255],
        [255,   0,   0, ..., 255, 255, 255],
        [255,   0,   0, ..., 255, 255, 255]], dtype=uint8))

In [ ]:
# 모폴로지 방식으로 하면 더 잘나올텐데 => 모핑 : 형태에 관련된 연산을 의미한다

In [ ]:
# 모폴로지 연습 (침식 / 팽창 순)

In [ ]:
import cv2
import numpy as np

img_path = 'img/morph_dot.png'
src = cv2.imread(img_path)

cv2.imshow('src',src)

kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (5,5)) 
# 1번째 인자 모양 => cv2.MORPH_RECT 사각형 , cv2.MORPH_ELLIPSE 원형 비슷한 커널, cv2.MORPH_CROSS 십자 커널
# 2번째 인자는 ksize => 튜플형 사이즈를 의미

print(kernel)

eroded = cv2.erode(src, kernel, iterations=1)

cv2.imshow('eroded',eroded)

cv2.waitKey()
cv2.destroyAllWindows()

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [8]:
import cv2
import numpy as np

img_path = 'img/morph_dot.png'
src = cv2.imread(img_path)

cv2.imshow('src',src)

kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (5,5)) 
# 1번째 인자 모양 => cv2.MORPH_RECT 사각형 , cv2.MORPH_ELLIPSE 원형 비슷한 커널, cv2.MORPH_CROSS 십자 커널
# 2번째 인자는 ksize => 튜플형 사이즈를 의미

print(kernel)

eroded = cv2.dilate(src, kernel, iterations=1)

cv2.imshow('eroded',eroded)

cv2.waitKey()
cv2.destroyAllWindows()

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
