In [1]:
print('hi')

hi


```
AI : 인간의 의도에 따라 답을 구하는 알고리즘들
ML : 단순하게 그래프를 구현하고 답을 구하는 데 최적화
DL : Dense를 쌓아서 기존 단순한 그래프를 여러 차원에 올려서 답을 구하는 형태

선생님 답변
AI : 인간을 모사하는 지능, 인간을 따라하는,
ML : TP Task Performance Experience 데이터를 통해 성능을 높이는 행위
DL : 신경망, Dense 은닉층을 쌓아서(4계층) MLP 퍼셉트론 주로 비정형데이터

데이터셋 구축이 필요하다
```

In [3]:
# %pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118

In [1]:
import torch
print(torch.cuda.is_available())

True


In [2]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
cpu = torch.FloatTensor([1, 2, 3])
gpu = torch.cuda.FloatTensor([1, 2, 3])
tensor = torch.rand((1, 1), device=device)
print(device)
print(cpu)
print(gpu)
print(tensor)

C:\Users\601\AppData\Local\Temp\ipykernel_12748\1924179652.py:4: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\tensor\python_tensor.cpp:80.)
  gpu = torch.cuda.FloatTensor([1, 2, 3])


cuda
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([[0.2393]], device='cuda:0')
