In [2]:
import cv2
print(cv2.getBuildInformation())


General configuration for OpenCV 4.12.0 =====================================
  Version control:               4.12.0

  Platform:
    Timestamp:                   2025-07-04T16:40:32Z
    Host:                        Windows 10.0.26100 AMD64
    CMake:                       3.24.2
    CMake generator:             Visual Studio 17 2022
    CMake build tool:            C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/MSBuild.exe
    MSVC:                        1944
    Configuration:               Debug Release
    Algorithm Hint:              ALGO_HINT_ACCURATE

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (17 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      AVX (9 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      FP16 (0 files):            + SSSE3 SS

In [3]:
import cv2 as cv

In [4]:
cv.imread('./opencv_logo.png', flags=cv.IMREAD_UNCHANGED) 

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       ...,

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], shape=(120, 98, 4), dtype=uint8)

In [5]:
opencv_logo_img = cv.imread('./opencv_logo.png')
opencv_logo_img.shape

(120, 98, 3)

In [6]:
opencv_logo_img2 = cv.imread('./opencv_logo.png', flags=cv.IMREAD_UNCHANGED) # flags 값을 IMREAD_UNCHANGED로 지정하여 알파값 까지 불러오기
opencv_logo_img2.shape 

(120, 98, 4)

In [ ]:
banana_img = cv.imread('./banana.jpg')

In [17]:
cv.imshow('banana',banana_img)
cv.waitKey(3000)
cv.destroyAllWindows()

In [18]:
import cv2 as cv

In [25]:
cv.imread('./opencv_logo.png', flags=cv.IMREAD_UNCHANGED)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       ...,

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], shape=(120, 98, 4), dtype=uint8)

In [37]:
opencv_logo_img = cv.imread('./opencv_logo.png', flags=cv.IMREAD_UNCHANGED)
opencv_logo_img.shape

(120, 98, 4)

In [40]:
cv.imshow('opencv',opencv_logo_img)
cv.waitKey()
cv.destroyAllWindows()

In [42]:
opencv_logo_img[:,:,3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(120, 98), dtype=uint8)

In [ ]:
cv.imshow('opencv',opencv_logo_img[:,:,3])
cv.waitKey() # wait key 에 k값을 대입하면 k millisecond 후에 닫힘
cv.destroyAllWindows()

## 그레이 스케일로 불러오기

In [51]:
cv.imread('./img/soccer.jpg', flags=cv.IMREAD_GRAYSCALE)

array([[109, 110, 107, ..., 110, 116, 115],
       [106, 108, 106, ..., 114, 112, 112],
       [105, 106, 106, ..., 107, 113, 113],
       ...,
       [154, 151, 149, ..., 142, 139, 140],
       [155, 151, 148, ..., 140, 138, 138],
       [154, 153, 150, ..., 138, 138, 138]],
      shape=(948, 1434), dtype=uint8)

In [97]:
soccer_gray_img = cv.imread('./img/soccer.jpg', flags=cv.IMREAD_GRAYSCALE)
soccer_gray_img.shape

(948, 1434)

In [103]:
cv.imshow('soccer',soccer_gray_img)
cv.waitKey()
cv.destroyAllWindows()

## 불러온 이미지를 GRAY로 바꾸기

In [88]:
soccer_img = cv.imread('./img/soccer.jpg')
soccer_img.shape

(948, 1434, 3)

In [ ]:
soccer_gray = cv.cvtColor(soccer_img, cv.COLOR_BGR2GRAY,)
cv.imshow('soccer',soccer_gray)
cv.waitKey()
cv.destroyAllWindows()

In [62]:
soccer_img[:,:,0] # blue channel

array([[162, 163, 162, ..., 112, 118, 117],
       [161, 163, 161, ..., 116, 114, 114],
       [162, 163, 163, ..., 111, 117, 117],
       ...,
       [ 81,  78,  76, ...,  60,  57,  58],
       [ 82,  78,  75, ...,  58,  56,  56],
       [ 81,  80,  77, ...,  56,  56,  56]],
      shape=(948, 1434), dtype=uint8)

In [ ]:
soccer_img[:,:,1] # green channel

array([[104, 105, 103, ..., 115, 121, 120],
       [101, 104, 102, ..., 119, 117, 117],
       [100, 102, 103, ..., 111, 117, 117],
       ...,
       [173, 170, 168, ..., 164, 161, 162],
       [174, 170, 167, ..., 162, 160, 160],
       [173, 172, 169, ..., 160, 160, 160]],
      shape=(948, 1434), dtype=uint8)

In [65]:
soccer_img[:,:,2] # red channel

array([[ 98,  99,  94, ..., 100, 106, 105],
       [ 95,  95,  93, ..., 104, 102, 102],
       [ 92,  92,  91, ...,  97, 103, 103],
       ...,
       [144, 141, 139, ..., 129, 126, 127],
       [145, 141, 138, ..., 127, 125, 125],
       [144, 143, 140, ..., 125, 125, 125]],
      shape=(948, 1434), dtype=uint8)

In [81]:
soccer_img[:,:,0][0,0], soccer_img[:,:,1][0,0], soccer_img[:,:,2][0,0]

(np.uint8(162), np.uint8(104), np.uint8(98))

In [85]:
soccer_img[0][0][0]

np.uint8(162)

In [86]:
import numpy

In [95]:
cv.imshow('soccer',soccer_img[:,:,1])
cv.waitKey()
cv.destroyAllWindows()

In [104]:
cv.VideoCapture()

< cv2.VideoCapture 000001954309F530>

In [115]:
cap = cv.VideoCapture(0)

In [116]:
import sys
if not cap.isOpened():
    sys.exit('카메라 연결 실패')

In [117]:
while True:
    ret, frame = cap.read()
    print(ret)
    cv.imshow('video',frame)
    cv.waitKey(1)
cap.release()
cv.destroyAllWindows()

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


KeyboardInterrupt: 